WIP: Product Link Functionality and UI changes
HelpfulHuman/ExperiencesWidgets pull request #177
Opened 2022-01-07 19:53 UTC by ilyaskarim

2022-01-11 18:16 UTC, ckeyes88 requested changes
Just a couple questions that may need changes.

2022-01-11 18:16 UTC, ckeyes88 commented on src/fullPageBookingForm/Components/Common/CustomForm/ProductAddons.tsx
> +              className={classnames({
Nice abstraction of the classnames.

2022-01-11 18:16 UTC, ckeyes88 commented on src/fullPageBookingForm/Components/Common/QuantitySelection/QuantitySelection.stories.tsx
> +  labels: defineLanguageDictionary("en-US"),
is this hard coded to english?

2022-01-11 18:16 UTC, ckeyes88 commented on src/fullPageBookingForm/Components/TimeslotGroup/TimeslotGroup.stories.tsx
> +        languageCode={"en-US"}
We shouldn't be hard coding the language.

2022-01-11 18:16 UTC, ckeyes88 commented on src/fullPageBookingForm/Components/TimeslotGroup/TimeslotGroup.stories.tsx
> +            languageCode: "en-US",
Same here.

2022-01-11 18:16 UTC, ckeyes88 commented on src/fullPageBookingForm/Components/Views/Confirmation/Confirmation.stories.tsx
> +  labels: defineLanguageDictionary("en-US"),
Hard coded language

2022-01-11 18:39 UTC, ilyaskarim commented on src/fullPageBookingForm/Components/Common/CustomForm/CustomForm.tsx
> +              <TextStyle text={"Attendee Info"} variant="body2"/>
Oh Yes I will fix this.

2022-01-11 18:40 UTC, ilyaskarim commented
@ckeyes88 the hard coded language is for development purposes only. I will add an option to change language from stories books playground.

2022-01-11 18:41 UTC, ilyaskarim commented on example/index.html
>      <!-- <link href="/dist/calendarBookingForm.css" rel="stylesheet" /> -->
@ckeyes88 Alright.

2022-01-11 19:19 UTC, ckeyes88 commented
@ilyaskarim sorry about the hard coded comments, I didn't catch that those were in story files. I think for now it's fine to leave as english and we can add other language support later.

2022-01-12 18:21 UTC, ckeyes88 commented
@ilyaskarim just let me know when this is ready to re-review so I know when pull it in.

2022-01-12 19:34 UTC, ilyaskarim commented
Hey chip, yesterday I was working on GitHub action. Today I'll execute this
and let you know.

On Wed, Jan 12, 2022, 11:21 PM Chip Keyes ***@***.***> wrote:

> @ilyaskarim <https://github.com/ilyaskarim> just let me know when this is
> ready to re-review so I know when pull it in.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HelpfulHuman/ExperiencesWidgets/pull/177#issuecomment-1011328697>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKD33VRUGO34UEH2BXPZNADUVXBDPANCNFSM5LPQUTVQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-14 18:04 UTC, ckeyes88 approved these changes

2022-01-14 18:05 UTC, merged