WIP: 3261 aggregate view
HelpfulHuman/ExperiencesWidgets pull request #52
Opened 2020-11-21 03:49 UTC by maksimhn

Notes & Assumptions:
- If an event is free, do not display price
- If there are multiple variants of an experience, find the lowest price and display `Starts at $[price]`
- In mobile view view selector is hidden, list view is shown by default, months name is shortened

In Profgress:
- `Avenir` font rolled up beside bundles
- CSS in active/hover state on next/prev buttons
- Setup manual/readme

2020-12-03 18:43 UTC, ckeyes88 requested changes
Just a couple things.

2020-12-03 18:43 UTC, ckeyes88 commented on src/widgets.ts
> +// const baseUrl = "__BASE_URL__/public/__ENV_NAME__";
@maksimhn can you switch this back to the production version?

2020-12-03 18:43 UTC, ckeyes88 commented on src/aggregateView/README.md
> +<link href="prod-v2.experiencesapp.services/dist/aggregateView.css" rel="stylesheet" />
@maksimhn I don't think you need this link here since if I recall I set up `loadWidget` to automatically include the css file so that it reduces the number of lines the merchant has to edit.

2020-12-04 02:18 UTC, maksimhn commented on src/widgets.ts
> +// const baseUrl = "__BASE_URL__/public/__ENV_NAME__";
done, thx

2020-12-04 02:20 UTC, maksimhn commented on src/aggregateView/README.md
> +<link href="prod-v2.experiencesapp.services/dist/aggregateView.css" rel="stylesheet" />
it sort of freezes without it
maybe we can take a look at it together during the UI session? I could've done something wrong with the bundle

2020-12-04 05:55 UTC, merged